name: Update data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1" # mondays at 12:00

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_crawler.txt

      - name: Update data
        run: python crawler.py
        shell: sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Data updated
